# Generated by Django 5.2 on 2025-08-31 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('email', 'Email de Phishing'), ('popup', 'Alerta de Malware'), ('chat', 'Chat de Ingeniería Social'), ('web', 'Página Web Falsa')], default='email', max_length=10)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.JSONField()),
                ('opciones', models.JSONField()),
                ('respuesta_correcta', models.CharField(max_length=100)),
                ('feedback_correcto', models.CharField(default='¡Correcto! Bien hecho.', max_length=255)),
                ('feedback_incorrecto', models.CharField(default='Esa no era la mejor opción.', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Insignia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255)),
                ('icono', models.CharField(help_text="Clase de Font Awesome, ej: 'fas fa-shield-alt'", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MensajeChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remitente', models.CharField(default='Chatbot', max_length=50)),
                ('texto', models.TextField()),
                ('opciones', models.JSONField(blank=True, null=True)),
                ('es_final', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Introduce tu nombre o un identificador único', max_length=100)),
                ('curso', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('genero', models.CharField(max_length=10)),
                ('puntaje_total', models.IntegerField(default=0)),
                ('insignias', models.ManyToManyField(blank=True, to='profiles.insignia')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_dada', models.CharField(max_length=100)),
                ('es_correcta', models.BooleanField()),
                ('escenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.escenario')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='profiles.perfilusuario')),
            ],
        ),
    ]
