# Generated by Django 5.2.3 on 2025-06-19 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('opciones', models.JSONField()),
                ('respuesta_correcta', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MensajeChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('opciones', models.JSONField()),
                ('es_final', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('genero', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_dada', models.CharField(max_length=100)),
                ('es_correcta', models.BooleanField()),
                ('escenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.escenario')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.participante')),
            ],
        ),
    ]
