# Generated by Django 5.2 on 2025-08-31 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminoGlosario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termino', models.CharField(max_length=100)),
                ('definicion', models.TextField()),
                ('ejemplo', models.TextField(blank=True, help_text='Un ejemplo práctico del término.', null=True)),
                ('icono', models.CharField(default='fas fa-question-circle', help_text="Clase de Font Awesome, ej: 'fas fa-shield-alt'", max_length=50)),
            ],
            options={
                'verbose_name': 'Término del glosario',
                'verbose_name_plural': 'Términos del glosario',
                'ordering': ['termino'],
            },
        ),
    ]
