# Generated by Django 5.2 on 2025-06-26 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajechat',
            name='remitente',
            field=models.CharField(default='Chatbot', max_length=50),
        ),
        migrations.AlterField(
            model_name='mensajechat',
            name='opciones',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='OpcionEscenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_opcion', models.CharField(max_length=200)),
                ('escenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones_relacionadas', to='profiles.escenario')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('genero', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='respuestausuario',
            name='participante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.perfilusuario'),
        ),
        migrations.DeleteModel(
            name='Participante',
        ),
    ]
