# Generated by Django 5.2 on 2025-06-26 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_mensajechat_remitente_alter_mensajechat_opciones_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajechat',
            name='next_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_messages', to='profiles.mensajechat'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='InteraccionChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_usuario', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('mensaje_chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacciones', to='profiles.mensajechat')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.perfilusuario')),
            ],
        ),
        migrations.DeleteModel(
            name='OpcionEscenario',
        ),
    ]
