# Generated by Django 5.2 on 2025-06-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_mensajechat_next_message_alter_perfilusuario_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensajechat',
            name='next_message',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='user',
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='nombre',
            field=models.CharField(default='Anónimo', help_text='Introduce tu nombre o un identificador único', max_length=100),
            preserve_default=False,
        ),
    ]
